// export const CatchAsyncError = (function)=>{
//     return(req,res,next)=>{
//         Promise.resolve(function(req,res,next)).catch(next);
//     }
// }